name = "Mbar4METTS"
uuid = "2a34d559-65b9-42dc-bee1-2af777994d17"
authors = ["Rafael D. Soares"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "1.13.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
