name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          version: '1.8'
          prefix: xvfb-run -s '-screen 0 1024x768x24'
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.8'
          prefix: xvfb-run -s '-screen 0 1024x768x24'
      - uses: julia-actions/cache@v2
        with:
          version: '1.8'
          prefix: xvfb-run -s '-screen 0 1024x768x24'

      - name: Add unregistered dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.develop(url="https://github.com/awietek/Dumper.jl")'

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: |
          xvfb-run -s '-screen 0 1024x768x24' julia --project=docs/ docs/make.jl